import cv2
import matplotlib.pyplot as plt

img = cv2.imread("img_8.jpeg")
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
smooth_3x3 = cv2.blur(img_rgb, (3, 3))
smooth_5x5 = cv2.blur(img_rgb, (5, 5))
plt.figure(figsize=(12, 4))
plt.subplot(1, 3, 1)
plt.imshow(img_rgb)
plt.title("Original Image")
plt.axis("off")
plt.subplot(1, 3, 2)
plt.imshow(smooth_3x3)
plt.title("3x3 Smoothed Image")
plt.axis("off")
plt.subplot(1, 3, 3)
plt.imshow(smooth_5x5)
plt.title("5x5 Smoothed Image")
plt.axis("off")
plt.tight_layout()
plt.show()
cv2.imwrite("smoothed_3x3.jpg", cv2.cvtColor(smooth_3x3, cv2.COLOR_RGB2BGR))
cv2.imwrite("smoothed_5x5.jpg", cv2.cvtColor(smooth_5x5, cv2.COLOR_RGB2BGR))
print("Color image smoothing completed.")
